In [7]:
from bs4 import BeautifulSoup
import requests

In [8]:
url = 'https://www.worldometers.info/world-population/population-by-country/'

page = requests.get(url)

soup = BeautifulSoup(page.text,'html')

In [23]:
table = soup.find('table','datatable w-full border border-zinc-200')

In [28]:
table.find_all('span')

[<span>#</span>,
 <span>Country (or dependency)</span>,
 <span>Population 2025</span>,
 <span>Yearly Change</span>,
 <span>Net Change</span>,
 <span>Density (P/KmÂ²)</span>,
 <span>Land Area (KmÂ²)</span>,
 <span>Migrants (net)</span>,
 <span>Fert. Rate</span>,
 <span>Median Age</span>,
 <span>Urban Pop %</span>,
 <span>World Share</span>]

In [30]:
world_columns = table.find_all('span')

In [32]:
world_column_titles = [columns.text for columns in world_columns]
print(world_column_titles)

['#', 'Country (or dependency)', 'Population 2025', 'Yearly Change', 'Net Change', 'Density (P/KmÂ²)', 'Land Area (KmÂ²)', 'Migrants (net)', 'Fert. Rate', 'Median Age', 'Urban Pop %', 'World Share']

In [42]:
import pandas as pd

df = pd.DataFrame(columns = world_column_titles)

In [37]:
table.find_all('td')

[<td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 1 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="india" href="/world-population/india-population/">India</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="1463865525" dir="ltr"> 1,463,865,525 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="89" dir="ltr"> 0.89% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="12929734" dir="ltr"> 12,929,734 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="492.35518920755146" dir="ltr"> 492 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2973190" dir="ltr"> 2,973,190 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-495753" dir="ltr"> â495,753 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="19430" dir="ltr"> 1.94 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="288290" dir="ltr"> 28.8 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3708" dir="ltr"> 37.1% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1778" dir="ltr"> 17.78% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 2 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="china" href="/world-population/china-population/">China</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="1416096094" dir="ltr"> 1,416,096,094 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-23" dir="ltr"> â0.23% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-3225184" dir="ltr"> â3,225,184 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="150.8376935712246" dir="ltr"> 151 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9388211" dir="ltr"> 9,388,211 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-268126" dir="ltr"> â268,126 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="10210" dir="ltr"> 1.02 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="401080" dir="ltr"> 40.1 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="6755" dir="ltr"> 67.5% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1720" dir="ltr"> 17.20% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 3 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="us" href="/world-population/us-population/">United States</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="347275807" dir="ltr"> 347,275,807 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="54" dir="ltr"> 0.54% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1849236" dir="ltr"> 1,849,236 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="37.96434480979336" dir="ltr"> 38 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9147420" dir="ltr"> 9,147,420 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1230663" dir="ltr"> 1,230,663 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16230" dir="ltr"> 1.62 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="385010" dir="ltr"> 38.5 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8276" dir="ltr"> 82.8% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="422" dir="ltr"> 4.22% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 4 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="indonesia" href="/world-population/indonesia-population/">Indonesia</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="285721236" dir="ltr"> 285,721,236 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="79" dir="ltr"> 0.79% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2233305" dir="ltr"> 2,233,305 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="157.72022941426496" dir="ltr"> 158 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1811570" dir="ltr"> 1,811,570 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-39509" dir="ltr"> â39,509 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="20960" dir="ltr"> 2.1 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="303790" dir="ltr"> 30.4 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="5963" dir="ltr"> 59.6% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="347" dir="ltr"> 3.47% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 5 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="pakistan" href="/world-population/pakistan-population/">Pakistan</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="255219554" dir="ltr"> 255,219,554 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="157" dir="ltr"> 1.57% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3950390" dir="ltr"> 3,950,390 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="331.07559412619344" dir="ltr"> 331 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="770880" dir="ltr"> 770,880 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-1235336" dir="ltr"> â1,235,336 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="34950" dir="ltr"> 3.5 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="206030" dir="ltr"> 20.6 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3439" dir="ltr"> 34.4% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="310" dir="ltr"> 3.10% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 6 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="nigeria" href="/world-population/nigeria-population/">Nigeria</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="237527782" dir="ltr"> 237,527,782 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="208" dir="ltr"> 2.08% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="4848304" dir="ltr"> 4,848,304 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="260.79886469690484" dir="ltr"> 261 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="910770" dir="ltr"> 910,770 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-15258" dir="ltr"> â15,258 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="42970" dir="ltr"> 4.3 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="181420" dir="ltr"> 18.1 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="5486" dir="ltr"> 54.9% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="289" dir="ltr"> 2.89% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 7 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="brazil" href="/world-population/brazil-population/">Brazil</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="212812405" dir="ltr"> 212,812,405 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="38" dir="ltr"> 0.38% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="813832" dir="ltr"> 813,832 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="25.461694228620242" dir="ltr"> 25 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8358140" dir="ltr"> 8,358,140 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-217283" dir="ltr"> â217,283 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16000" dir="ltr"> 1.6 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="348180" dir="ltr"> 34.8 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9137" dir="ltr"> 91.4% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="259" dir="ltr"> 2.59% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 8 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="bangladesh" href="/world-population/bangladesh-population/">Bangladesh</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="175686899" dir="ltr"> 175,686,899 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="122" dir="ltr"> 1.22% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2124535" dir="ltr"> 2,124,535 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1349.6727279711147" dir="ltr"> 1,350 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="130170" dir="ltr"> 130,170 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-402100" dir="ltr"> â402,100 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="21140" dir="ltr"> 2.11 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="259770" dir="ltr"> 26 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="4260" dir="ltr"> 42.6% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="213" dir="ltr"> 2.13% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 9 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="russia" href="/world-population/russia-population/">Russia</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="143997393" dir="ltr"> 143,997,393 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-57" dir="ltr"> â0.57% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-823030" dir="ltr"> â823,030 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8.792729807344138" dir="ltr"> 9 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16376870" dir="ltr"> 16,376,870 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-251822" dir="ltr"> â251,822 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="14650" dir="ltr"> 1.47 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="402970" dir="ltr"> 40.3 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="7504" dir="ltr"> 75% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="175" dir="ltr"> 1.75% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 10 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="ethiopia" href="/world-population/ethiopia-population/">Ethiopia</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="135472051" dir="ltr"> 135,472,051 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="258" dir="ltr"> 2.58% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3412284" dir="ltr"> 3,412,284 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="135.472051" dir="ltr"> 135 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1000000" dir="ltr"> 1,000,000 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="24054" dir="ltr"> 24,054 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="38060" dir="ltr"> 3.81 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="191330" dir="ltr"> 19.1 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2250" dir="ltr"> 22.5% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="165" dir="ltr"> 1.65% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 11 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="mexico" href="/world-population/mexico-population/">Mexico</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="131946900" dir="ltr"> 131,946,900 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="83" dir="ltr"> 0.83% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1085893" dir="ltr"> 1,085,893 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="67.87566552637671" dir="ltr"> 68 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1943950" dir="ltr"> 1,943,950 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-108037" dir="ltr"> â108,037 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="18690" dir="ltr"> 1.87 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="296230" dir="ltr"> 29.6 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8786" dir="ltr"> 87.9% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="160" dir="ltr"> 1.60% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 12 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="japan" href="/world-population/japan-population/">Japan</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="123103479" dir="ltr"> 123,103,479 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-52" dir="ltr"> â0.52% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-649562" dir="ltr"> â649,562 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="337.68149936223614" dir="ltr"> 338 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="364555" dir="ltr"> 364,555 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="140579" dir="ltr"> 140,579 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="12250" dir="ltr"> 1.23 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="497920" dir="ltr"> 49.8 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9313" dir="ltr"> 93.1% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="150" dir="ltr"> 1.50% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 13 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="egypt" href="/world-population/egypt-population/">Egypt</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="118365995" dir="ltr"> 118,365,995 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="157" dir="ltr"> 1.57% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1827737" dir="ltr"> 1,827,737 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="118.90702194987192" dir="ltr"> 119 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="995450" dir="ltr"> 995,450 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-57305" dir="ltr"> â57,305 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="27080" dir="ltr"> 2.71 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="244780" dir="ltr"> 24.5 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="4091" dir="ltr"> 40.9% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="144" dir="ltr"> 1.44% </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 14 </td>,
 <td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="philippines" href="/world-population/philippines-population/">Philippines</a> </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="116786962" dir="ltr"> 116,786,962 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="81" dir="ltr"> 0.81% </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="943292" dir="ltr"> 943,292 </td>,
 <td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="391.6791159405708" dir="ltr"> 392 </td>,

In [38]:
 table.find_all('tr')

[<tr> <th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true"> <span>#</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true"> <span>Country (or dependency)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Population 2025</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Yearly Change</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Net Change</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Density (P/KmÂ²)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Land Area (KmÂ²)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Migrants (net)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Fert. Rate</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Median Age</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Urban Pop %</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>World Share</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th> </tr>,
 <tr id="india"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 1 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="india" href="/world-population/india-population/">India</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="1463865525" dir="ltr"> 1,463,865,525 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="89" dir="ltr"> 0.89% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="12929734" dir="ltr"> 12,929,734 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="492.35518920755146" dir="ltr"> 492 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2973190" dir="ltr"> 2,973,190 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-495753" dir="ltr"> â495,753 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="19430" dir="ltr"> 1.94 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="288290" dir="ltr"> 28.8 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3708" dir="ltr"> 37.1% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1778" dir="ltr"> 17.78% </td> </tr>,
 <tr id="china"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 2 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="china" href="/world-population/china-population/">China</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="1416096094" dir="ltr"> 1,416,096,094 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-23" dir="ltr"> â0.23% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-3225184" dir="ltr"> â3,225,184 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="150.8376935712246" dir="ltr"> 151 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9388211" dir="ltr"> 9,388,211 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-268126" dir="ltr"> â268,126 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="10210" dir="ltr"> 1.02 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="401080" dir="ltr"> 40.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="6755" dir="ltr"> 67.5% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1720" dir="ltr"> 17.20% </td> </tr>,
 <tr id="us"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 3 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="us" href="/world-population/us-population/">United States</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="347275807" dir="ltr"> 347,275,807 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="54" dir="ltr"> 0.54% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1849236" dir="ltr"> 1,849,236 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="37.96434480979336" dir="ltr"> 38 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9147420" dir="ltr"> 9,147,420 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1230663" dir="ltr"> 1,230,663 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16230" dir="ltr"> 1.62 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="385010" dir="ltr"> 38.5 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8276" dir="ltr"> 82.8% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="422" dir="ltr"> 4.22% </td> </tr>,
 <tr id="indonesia"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 4 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="indonesia" href="/world-population/indonesia-population/">Indonesia</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="285721236" dir="ltr"> 285,721,236 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="79" dir="ltr"> 0.79% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2233305" dir="ltr"> 2,233,305 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="157.72022941426496" dir="ltr"> 158 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1811570" dir="ltr"> 1,811,570 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-39509" dir="ltr"> â39,509 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="20960" dir="ltr"> 2.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="303790" dir="ltr"> 30.4 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="5963" dir="ltr"> 59.6% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="347" dir="ltr"> 3.47% </td> </tr>,
 <tr id="pakistan"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 5 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="pakistan" href="/world-population/pakistan-population/">Pakistan</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="255219554" dir="ltr"> 255,219,554 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="157" dir="ltr"> 1.57% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3950390" dir="ltr"> 3,950,390 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="331.07559412619344" dir="ltr"> 331 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="770880" dir="ltr"> 770,880 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-1235336" dir="ltr"> â1,235,336 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="34950" dir="ltr"> 3.5 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="206030" dir="ltr"> 20.6 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3439" dir="ltr"> 34.4% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="310" dir="ltr"> 3.10% </td> </tr>,
 <tr id="nigeria"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 6 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="nigeria" href="/world-population/nigeria-population/">Nigeria</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="237527782" dir="ltr"> 237,527,782 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="208" dir="ltr"> 2.08% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="4848304" dir="ltr"> 4,848,304 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="260.79886469690484" dir="ltr"> 261 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="910770" dir="ltr"> 910,770 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-15258" dir="ltr"> â15,258 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="42970" dir="ltr"> 4.3 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="181420" dir="ltr"> 18.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="5486" dir="ltr"> 54.9% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="289" dir="ltr"> 2.89% </td> </tr>,
 <tr id="brazil"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 7 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="brazil" href="/world-population/brazil-population/">Brazil</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="212812405" dir="ltr"> 212,812,405 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="38" dir="ltr"> 0.38% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="813832" dir="ltr"> 813,832 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="25.461694228620242" dir="ltr"> 25 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8358140" dir="ltr"> 8,358,140 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-217283" dir="ltr"> â217,283 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16000" dir="ltr"> 1.6 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="348180" dir="ltr"> 34.8 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9137" dir="ltr"> 91.4% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="259" dir="ltr"> 2.59% </td> </tr>,
 <tr id="bangladesh"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 8 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="bangladesh" href="/world-population/bangladesh-population/">Bangladesh</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="175686899" dir="ltr"> 175,686,899 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="122" dir="ltr"> 1.22% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2124535" dir="ltr"> 2,124,535 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1349.6727279711147" dir="ltr"> 1,350 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="130170" dir="ltr"> 130,170 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-402100" dir="ltr"> â402,100 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="21140" dir="ltr"> 2.11 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="259770" dir="ltr"> 26 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="4260" dir="ltr"> 42.6% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="213" dir="ltr"> 2.13% </td> </tr>,
 <tr id="russia"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 9 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="russia" href="/world-population/russia-population/">Russia</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="143997393" dir="ltr"> 143,997,393 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-57" dir="ltr"> â0.57% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-823030" dir="ltr"> â823,030 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8.792729807344138" dir="ltr"> 9 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16376870" dir="ltr"> 16,376,870 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-251822" dir="ltr"> â251,822 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="14650" dir="ltr"> 1.47 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="402970" dir="ltr"> 40.3 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="7504" dir="ltr"> 75% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="175" dir="ltr"> 1.75% </td> </tr>,
 <tr id="ethiopia"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 10 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-country="ethiopia" href="/world-population/ethiopia-population/">Ethiopia</a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="135472051" dir="ltr"> 135,472,051 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="258" dir="ltr"> 2.58% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3412284" dir="ltr"> 3,412,284 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="135.472051" dir="ltr"> 135 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1000000" dir="ltr"> 1,000,000 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="24054" dir="ltr"> 24,054 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="38060" dir="ltr"> 3.81 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="191330" dir="ltr"> 19.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2250" dir="ltr"> 22.5% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="165" dir="ltr"> 1.65% </td> </tr>,

In [44]:
world_rows = table.find_all('tr')

In [49]:
for row in world_rows [1:]:
    row_data = row.find_all('td')
    individual_row_data=[data.text for data in row_data]
    
    length = len(df)
    df.loc[length]= individual_row_data
   

df

,#,Country (or dependency),Population 2025,Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,"1,463,865,525",0.89%,"12,929,734",492,"2,973,190","â495,753",1.94,28.8,37.1%,17.78%
1,2,China,"1,416,096,094",â0.23%,"â3,225,184",151,"9,388,211","â268,126",1.02,40.1,67.5%,17.20%
2,3,United States,"347,275,807",0.54%,"1,849,236",38,"9,147,420","1,230,663",1.62,38.5,82.8%,4.22%
3,4,Indonesia,"285,721,236",0.79%,"2,233,305",158,"1,811,570","â39,509",2.1,30.4,59.6%,3.47%
4,5,Pakistan,"255,219,554",1.57%,"3,950,390",331,"770,880","â1,235,336",3.5,20.6,34.4%,3.10%
...,...,...,...,...,...,...,...,...,...,...,...,...
694,229,Montserrat,"4,359",â0.68%,â30,44,100,â9,1.45,41.6,11.5%,0.000053%
695,230,Falkland Islands,"3,469",â0.03%,â1,0,"12,170",â17,1.7,42.8,68%,0.000042%
696,231,Tokelau,"2,608",4.07%,102,261,10,53,2.57,27.3,,0.000032%
697,232,Niue,"1,821",0.11%,2,7,260,3,2.46,35.7,44.5%,0.000022%
698,233,Holy See,501,1.01%,5,"1,253",0,13,1,57.4,,0.0000061%

In [43]:
len(df)

0

In [54]:
df.head(234)

,#,Country (or dependency),Population 2025,Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,"1,463,865,525",0.89%,"12,929,734",492,"2,973,190","â495,753",1.94,28.8,37.1%,17.78%
1,2,China,"1,416,096,094",â0.23%,"â3,225,184",151,"9,388,211","â268,126",1.02,40.1,67.5%,17.20%
2,3,United States,"347,275,807",0.54%,"1,849,236",38,"9,147,420","1,230,663",1.62,38.5,82.8%,4.22%
3,4,Indonesia,"285,721,236",0.79%,"2,233,305",158,"1,811,570","â39,509",2.1,30.4,59.6%,3.47%
4,5,Pakistan,"255,219,554",1.57%,"3,950,390",331,"770,880","â1,235,336",3.5,20.6,34.4%,3.10%
...,...,...,...,...,...,...,...,...,...,...,...,...
229,230,Falkland Islands,"3,469",â0.03%,â1,0,"12,170",â17,1.7,42.8,68%,0.000042%
230,231,Tokelau,"2,608",4.07%,102,261,10,53,2.57,27.3,,0.000032%
231,232,Niue,"1,821",0.11%,2,7,260,3,2.46,35.7,44.5%,0.000022%
232,233,Holy See,501,1.01%,5,"1,253",0,13,1,57.4,,0.0000061%
233,1,India,"1,463,865,525",0.89%,"12,929,734",492,"2,973,190","â495,753",1.94,28.8,37.1%,17.78%

In [57]:
df2 = df.drop_duplicates()

In [58]:
df2.to_csv(r'C:\Users\gunav\OneDrive\Desktop\Pyhton Doc\World_population_scrapped.csv')