In [3]:
import pandas as pd
import numpy as np

# Data Cleaning with Duplicates

In [4]:
data = {
    'Transaction ID': [101, 102, 103, 103, 104, 105, 106],
    'Customer Name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Ron Weasley', 'Draco Malfoy', 'Luna Lovegood', 'Draco Malfoy'],
    'Wand': ['Elder Wand', 'Vine Wood', 'Hawthorn', 'Hawthorn', 'Dragon Heartstring', 'Thestral Tail Hair', 'Dragon Heartstring'],
    'Price': [100, 75, 50, 50, 80, 60, 80]
}

Wand_Transactions = pd.DataFrame(data)

Wand_Transactions

   Transaction ID     Customer Name                Wand  Price
0             101      Harry Potter          Elder Wand    100
1             102  Hermione Granger           Vine Wood     75
2             103       Ron Weasley            Hawthorn     50
3             103       Ron Weasley            Hawthorn     50
4             104      Draco Malfoy  Dragon Heartstring     80
5             105     Luna Lovegood  Thestral Tail Hair     60
6             106      Draco Malfoy  Dragon Heartstring     80

In [5]:
data = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Harry', 'Draco', 'Luna', 'Harry'],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Potter', 'Malfoy', 'Lovegood', 'Potter'],
    'Hogwarts House': ['Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Slytherin', 'Ravenclaw', 'Gryffindor'],
    'Favorite Class': ['Defense Against the Dark Arts', 'Potions', 'Charms', 'Quidditch', 'Transfiguration', 'Care of Magical Creatures', 'Herbology']
}

Class_List = pd.DataFrame(data)

Class_List

  First Name Last Name Hogwarts House                 Favorite Class
0      Harry    Potter     Gryffindor  Defense Against the Dark Arts
1   Hermione   Granger     Gryffindor                        Potions
2        Ron   Weasley     Gryffindor                         Charms
3      Harry    Potter     Gryffindor                      Quidditch
4      Draco    Malfoy      Slytherin                Transfiguration
5       Luna  Lovegood      Ravenclaw      Care of Magical Creatures
6      Harry    Potter     Gryffindor                      Herbology

In [5]:
Wand_Transactions.drop_duplicates()

   Transaction ID     Customer Name                Wand  Price
0             101      Harry Potter          Elder Wand    100
1             102  Hermione Granger           Vine Wood     75
2             103       Ron Weasley            Hawthorn     50
4             104      Draco Malfoy  Dragon Heartstring     80
5             105     Luna Lovegood  Thestral Tail Hair     60
6             106      Draco Malfoy  Dragon Heartstring     80

In [6]:
Class_List.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

# Standardizing Data

In [6]:
data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'full_name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Draco Malfoy', 'Luna Lovegood', 'Neville Longbottom', 'Ginny Weasley', 'Fred Weasley', 'George Weasley', 'Cho Chang'],
    'phone_number': ['(123) 456-7890', '555-123-4567', '9876543210', '123.456.7890', '(123)-4567890', '987-654-3210', '123 456 7890', '1234567890', '+7890123456', '012-345-6789']
}

Bad_Numbers = pd.DataFrame(data)
Bad_Numbers

   student_id           full_name    phone_number
0           1        Harry Potter  (123) 456-7890
1           2    Hermione Granger    555-123-4567
2           3         Ron Weasley      9876543210
3           4        Draco Malfoy    123.456.7890
4           5       Luna Lovegood   (123)-4567890
5           6  Neville Longbottom    987-654-3210
6           7       Ginny Weasley    123 456 7890
7           8        Fred Weasley      1234567890
8           9      George Weasley     +7890123456
9          10           Cho Chang    012-345-6789

In [7]:
Bad_Numbers['phone_number'] = Bad_Numbers['phone_number'].str.replace( '\D' , '',regex=True)

In [8]:
Bad_Numbers['phone_number']

0    1234567890
1    5551234567
2    9876543210
3    1234567890
4    1234567890
5    9876543210
6    1234567890
7    1234567890
8    7890123456
9    0123456789
Name: phone_number, dtype: object

In [9]:
len(Bad_Numbers[Bad_Numbers['phone_number'].str.len()!=10])

0

In [10]:
Bad_Numbers['phone_number'] = Bad_Numbers['phone_number'].str[:3]+'-'+Bad_Numbers['phone_number'].str[3:6]+'-'+Bad_Numbers['phone_number'].str[6:]

In [50]:
Bad_Numbers

   student_id           full_name  phone_number
0           1        Harry Potter  123-456-7890
1           2    Hermione Granger  555-123-4567
2           3         Ron Weasley  987-654-3210
3           4        Draco Malfoy  123-456-7890
4           5       Luna Lovegood  123-456-7890
5           6  Neville Longbottom  987-654-3210
6           7       Ginny Weasley  123-456-7890
7           8        Fred Weasley  123-456-7890
8           9      George Weasley  789-012-3456
9          10           Cho Chang  012-345-6789

In [11]:
data = {
    'Full Name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Draco Malfoy', 'Luna Lovegood', 'Gregory Goyle'],
    'Voldemort_Bad': ['Y', 'Yes', 'Yes', 'No', 'yes', 'Nope!']
}

Voldy = pd.DataFrame(data)

Voldy

          Full Name Voldemort_Bad
0      Harry Potter             Y
1  Hermione Granger           Yes
2       Ron Weasley           Yes
3      Draco Malfoy            No
4     Luna Lovegood           yes
5     Gregory Goyle         Nope!

In [69]:
Voldy['Voldemort_Bad'] = Voldy['Voldemort_Bad'].str.replace(r'\b[Yy]\w*\b' ,'Yes',regex =True)

In [70]:
Voldy['Voldemort_Bad']

0      Yes
1      Yes
2      Yes
3       No
4      Yes
5    Nope!
Name: Voldemort_Bad, dtype: object

In [73]:
Voldy['Voldemort_Bad'] = Voldy['Voldemort_Bad'].str.replace(r'\b[Nn]\w*\b' ,'No',regex =True)

In [74]:
Voldy['Voldemort_Bad']

0    Yes
1    Yes
2    Yes
3     No
4    Yes
5    No!
Name: Voldemort_Bad, dtype: object

In [77]:
Voldy['Voldemort_Bad'] = Voldy['Voldemort_Bad'].str.replace(r'!','',regex =True)

In [78]:
Voldy

          Full Name Voldemort_Bad
0      Harry Potter           Yes
1  Hermione Granger           Yes
2       Ron Weasley           Yes
3      Draco Malfoy            No
4     Luna Lovegood           Yes
5     Gregory Goyle            No

In [79]:
Voldy.groupby('Voldemort_Bad').count()

               Full Name
Voldemort_Bad
No                     2
Yes                    4

In [12]:
data = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Hermione', 'Ronald', 'Harry', 'Hermion', 'Ron'],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Grangar', 'Weasly', 'Poter', 'Graner', 'Weaseley'],
    'Age': [18, 17, 18, 17, 18, 18, 17, 18],
    'Social Security Number': ['123-45-6789', '987-65-4321', '555-55-5555', '987-65-4321', '555-55-5555',
                               '123-45-6789', '987-65-4321', '555-55-5555']
}

Hogwarts_Students = pd.DataFrame(data)

Hogwarts_Students

  First Name Last Name  Age Social Security Number
0      Harry    Potter   18            123-45-6789
1   Hermione   Granger   17            987-65-4321
2        Ron   Weasley   18            555-55-5555
3   Hermione   Grangar   17            987-65-4321
4     Ronald    Weasly   18            555-55-5555
5      Harry     Poter   18            123-45-6789
6    Hermion    Graner   17            987-65-4321
7        Ron  Weaseley   18            555-55-5555

In [88]:
Hogwarts_Students.groupby('Social Security Number').ngroup().reset_index(name = 'same_student_id')

   index  same_student_id
0      0                0
1      1                2
2      2                1
3      3                2
4      4                1
5      5                0
6      6                2
7      7                1

In [83]:
Hogwarts_Students.groupby(Hogwarts_Students.groupby('Social Security Number').ngroup())['Social Security Number'].count()

0    2
1    3
2    3
Name: Social Security Number, dtype: int64

In [90]:
Hogwarts_Students.groupby(Hogwarts_Students['First Name'].str[:3]+Hogwarts_Students['Last Name'].str[:3]).ngroup()+1

0    1
1    2
2    3
3    2
4    3
5    1
6    2
7    3
dtype: int64

In [99]:
data = {
    'First Name': ['Harry', 'Hermione?', 'Ron', 'Hermione', 'Ron_', 'Harry!', 'Hermione', 'Ron'],
    'Last Name': ['"Potter"', 'Granger', 'Weasley', 'Granger', 'Weasley...', 'Potter', 'Granger', 'Weasley'],
    'Age': [18, 17, 18, 17, 18, 18, 17, 18]
}

Hogwarts_Students2 = pd.DataFrame(data)

Hogwarts_Students2

  First Name   Last Name  Age
0      Harry    "Potter"   18
1  Hermione?     Granger   17
2        Ron     Weasley   18
3   Hermione     Granger   17
4       Ron_  Weasley...   18
5     Harry!      Potter   18
6   Hermione     Granger   17
7        Ron     Weasley   18

In [100]:
Hogwarts_Students2['First Name'] = Hogwarts_Students2['First Name'].str.replace(r'[^a-zA-z]','', regex =True)

In [101]:
Hogwarts_Students2['First Name']= Hogwarts_Students2['First Name'].str.replace(r'_','', regex =True)

In [102]:
  Hogwarts_Students2['Last Name']= Hogwarts_Students2['Last Name'].str.replace(r'[^a-zA-z]','', regex =True)

In [103]:
Hogwarts_Students2

  First Name Last Name  Age
0      Harry    Potter   18
1   Hermione   Granger   17
2        Ron   Weasley   18
3   Hermione   Granger   17
4        Ron   Weasley   18
5      Harry    Potter   18
6   Hermione   Granger   17
7        Ron   Weasley   18

In [138]:
data = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Draco', 'Luna', np.nan, np.nan],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Malfoy', np.nan, 'Lovegood', np.nan],
    'Hogwarts House': ['Gryffindor', 'Gryffindor', 'Gryffindor', np.nan, 'Ravenclaw', 'Gryffindor', np.nan],
    'Age': [18, 17, np.nan, 16, 16, 18, np.nan]
}

Nulls = pd.DataFrame(data)

Nulls

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor   NaN
3      Draco    Malfoy            NaN  16.0
4       Luna       NaN      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0
6        NaN       NaN            NaN   NaN

In [143]:
Nulls['Age'] = Nulls.groupby('Hogwarts House')['Age'].transform(lambda x : x.fillna (x.median()))

In [ ]:
df['review_rating'] = df.groupby('category')['review_rating'].transform(lambda x: x.fillna(x.median()))

In [148]:
Nulls['Age'] = Nulls['Age'].fillna(Nulls['Age'].mean())

In [149]:
Nulls

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor  18.0
3      Draco    Malfoy            NaN  17.4
4       Luna       NaN      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0
6        NaN       NaN            NaN  17.4

In [152]:
Nulls.fillna(method = 'ffill')

C:\Users\gunav\AppData\Local\Temp\ipykernel_6900\2278595994.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Nulls.fillna(method = 'ffill')

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor  18.0
3      Draco    Malfoy     Gryffindor  17.4
4       Luna    Malfoy      Ravenclaw  16.0
5       Luna  Lovegood     Gryffindor  18.0
6       Luna  Lovegood     Gryffindor  17.4

In [177]:
Nulls.drop(Nulls[Nulls['Age']>17.0].index)

  First Name Last Name Hogwarts House   Age
1   Hermione   Granger     Gryffindor  17.0
4       Luna       NaN      Ravenclaw  16.0

In [151]:
Nulls.fillna(method = 'bfill')

C:\Users\gunav\AppData\Local\Temp\ipykernel_6900\3783052799.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Nulls.fillna(method = 'bfill')

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor  18.0
3      Draco    Malfoy      Ravenclaw  17.4
4       Luna  Lovegood      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0
6        NaN       NaN            NaN  17.4

In [154]:
Nulls.replace(np.nan,'unknown')

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor  18.0
3      Draco    Malfoy        unknown  17.4
4       Luna   unknown      Ravenclaw  16.0
5    unknown  Lovegood     Gryffindor  18.0
6    unknown   unknown        unknown  17.4

In [155]:
data = {
    'First name': ['Harry', 'Harry', 'Hermione', 'Hermione', 'Ron', 'Ron', 'Draco', 'Draco', 'Luna', 'Luna', 'Neville', 'Neville', 'Ginny', 'Ginny', 'Fred', 'Fred', 'George', 'George', 'Cho', 'Cho', 'Cedric', 'Cedric', 'Sirius', 'Sirius', 'Remus', 'Remus'],
    'Last name': ['Potter', np.nan, 'Granger', 'Granger', 'Weasley', 'Weasley', 'Malfoy', 'Malfoy', 'Lovegood', 'Lovegood', 'Longbottom', 'Longbottom', 'Weasley', 'Weasley', 'Weasley', 'Weasley', 'Weasley', 'Weasley', 'Chang', 'Chang', 'Diggory', 'Diggory', 'Black', 'Black', 'Lupin', 'Lupin'],
    'Hogwarts house': ['Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', np.nan, 'Gryffindor', 'Slytherin', 'Slytherin', 'Ravenclaw', 'Ravenclaw', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Ravenclaw', 'Ravenclaw', 'Hufflepuff', 'Hufflepuff', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor'],
    'Transaction_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, np.nan, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
    'Transaction_amount': [50, 75, 30, 20, 45, 60, 55, 80, 65, 70, 40, 85, 90, 55, 60, 75, 80, 35, 40, 95, 50, 65, 70, 25, 30, 45]
}

df = pd.DataFrame(data)
df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry         NaN     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley            NaN             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor             NaN                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

In [167]:
df['Last name'] = df['Last name'].fillna(df.groupby(['First name','Hogwarts house'])['Last name'].transform('first'))

In [168]:
df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry      Potter     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley            NaN             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor             NaN                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

In [170]:
df['Hogwarts house'] = df['Hogwarts house'].fillna(df.groupby(['First name','Last name'])['Hogwarts house'].transform('first'))

In [171]:
df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry      Potter     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley     Gryffindor             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor             NaN                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

In [175]:
df['Transaction_ID'] = df['Transaction_ID'].fillna( df['Transaction_ID'].ffill() + 1)

In [176]:
df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry      Potter     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley     Gryffindor             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor            15.0                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45